### ISSUE TITLE
Error: Table 'scorecardv5.logisticsfaq' doesn't exist

### ISSUE THREAD

**Issue by Lexor42** [SeanFranklin/hemaScorecard#138]
Hello,

First of all, thank you very much for providing this tool!

I am currently having issues to set it up in a local Docker environment:
After I created an event, the page gets blank due to this error:

`***Error: Table 'scorecardv5.logisticsfaq' doesn't exist`

It seems to be that the DB schema provided in `/includes/Tables - Docker SQL Stuff.sql` is outdated.

Could you provide an update? Thanks in advance

Cheers

**Comment by l-penington** [comment]
Hello,

I'm working on getting an instance of this set up for my club's internal use, and hitting the same issue as you.

I've forked the repo and added my best guess of the changes required to get it working. I'll be testing it out over the next few weeks.

The relevant branch is available [here](https://github.com/l-penington/hemaScorecard/tree/bugfix/schema_inconsistent_with_php).

I hope this helps!

**Comment by Lexor42** [comment]
> Hello,
> 
> I'm working on getting an instance of this set up for my club's internal use, and hitting the same issue as you.
> 
> I've forked the repo and added my best guess of the changes required to get it working. I'll be testing it out over the next few weeks.
> 
> The relevant branch is available [here](https://github.com/l-penington/hemaScorecard/tree/bugfix/schema_inconsistent_with_php).
> 
> I hope this helps!
